[package]
name = "rustix-api"
version = "0.1.0"
authors = ["Kevin Faveri <kevin@faveri.dev>"]
edition = "2021"
rust-version = "1.76.0"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_derive = "1.0.197"
futures = "0.3.30"
thiserror = "1.0.57"
axum = { version = "0.7.4" }
axum-extra = { version = "0.9.2", features = ["typed-header"] }
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tower-http = { version = "0.5.2", features = [
  "trace",
  "compression-br",
  "propagate-header",
  "sensitive-headers",
  "cors",
] }
http = "1.1.0"
chrono = "0.4.35"
async-trait = "0.1.77"
jsonwebtoken = "9.2.0"
bcrypt = "0.15.0"
validator = { version = "0.17.0", features = ["derive"] }
lazy_static = "1.4.0"
mime = "0.3.17"
bytes = "1.5.0"
dotenvy = "0.15.7"
sqlx = { version = "0.7.3", features = [
  "runtime-async-std-native-tls",
  "postgres",
  "uuid",
  "chrono",
] }
uuid = { version = "1.2.2", features = ["serde", "v4"] }


[dev-dependencies]
assert-json-diff = "2.0.2"
reqwest = { version = "0.11.24", features = ["json"] }
pretty_assertions = "1.4.0"
