# This file is used for development only; and serves to setup auxiliary services to the main application, which is often run natively
version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: rustix_sqlx
    ports:
      - "6500:5432"